# Generated by Django 2.1.2 on 2018-10-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.IntegerField(null=True)),
                ('sub2', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Marks',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('USN', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddField(
            model_name='marks',
            name='USN',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Students'),
        ),
    ]
