# Generated by Django 2.1.2 on 2018-10-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20181007_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='phone',
            new_name='Phone',
        ),
    ]
