# Generated by Django 2.1.2 on 2018-11-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20181101_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('DCode', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('DName', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
