# Generated by Django 2.1.2 on 2018-11-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Depart'),
        ),
    ]
