# Generated by Django 2.1.2 on 2018-11-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20181101_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depart',
            name='id',
        ),
        migrations.AlterField(
            model_name='depart',
            name='DCode',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
