# Generated by Django 2.1.2 on 2018-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20181101_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='depart',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depart',
            name='DCode',
            field=models.CharField(max_length=3),
        ),
    ]
