# Generated by Django 2.1.2 on 2018-11-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20181101_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depart',
            name='id',
        ),
        migrations.AlterField(
            model_name='depart',
            name='DCode',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Depart'),
        ),
    ]
