# Generated by Django 2.1.2 on 2018-11-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20181101_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Department',
        ),
        migrations.AddField(
            model_name='students',
            name='Department',
            field=models.ManyToManyField(to='student.Depart'),
        ),
    ]
