# Generated by Django 2.1.2 on 2018-11-01 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20181101_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Depart'),
        ),
    ]
