# Generated by Django 2.1.2 on 2018-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20181101_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='USN',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
